### ISSUE TITLE
ReflectionContainer could resolve "named" arguments

### ISSUE THREAD

**Issue by Arcesilas** [thephpleague/container#142] opened 2018-03-31 00:24 UTC
Hi,

Just figured out that this example does not work:

```php
class Foo
{
    public $bar;

    public function __construct($bar)
    {
        $this->bar = $bar;
    }
}

$container = new Container();
$container->delegate(new ReflectionContainer());

$container->add('bar', 'Hello world!');

var_dump($container->get('Foo')->bar);
```

Obviously, it throws a `NotFoundException` in `ArgumentResolverTrait`.

Since we know the name of the argument (ie: the name of the variable used in the constructor signature), it could be easy to check if the container has it before the exception is thrown, in `reflectArguments` method:

```php
            if ($this->getContainer()->has($name)) {
                return $this->getContainer()->get($name);
            }
```

But I have no idea whether it has any consequences (any possible loop, since it looks back in the "main" container)? It's not possible to 

Would it be worth adding this feature? (I must say I like it...)

**Comment by philipobenito** [comment] 2018-03-31 06:09
Hi, this is by design. We only reflect on something that is not registered with the container and has a type hint or a default value. 

Whilst you're correct in your assessment that it would be easy to reflect on the name of the variable, it's also adds much more overhead to an operation that is already pretty heavy in real world scenarios.

I always recommend *not* using the reflection container at all because there is always a temptation to not convert that in to a dependency map when moving to production because it "just works". 

My experience working with people, is that causes a problem for developers that are new to the concepts, I found in many cases (with older versions that implemented reflection by default especially) that they would implement without understanding of what was happening and therefore no knowledge of what consequences any changes they made would have.

It's not something I would consider putting in to the main component, however, it's built in a way that if you want that feature, you could easily extend the `ReflectionContainer` and add that as a delegate instead.

**Closed by philipobenito** 2018-03-31 06:09 UTC

**Comment by Arcesilas** [comment] 2018-03-31 07:53
Thanks for for your enlightening answer!

**Comment by Arcesilas** [comment] 2018-04-02 08:56
Hi, hope you don't mind I ask another question in this thread?

Argument resolution with `ReflectionContainer` allows to automatically resolve dependencies for DI and IoC. You discourage using `ReflectionContainer` to prevent from hiding the resolution and prefer a mapping (in a ServiceProvider preferably).
I understand all that perfectly, but what about storing variables in the container? Since simple variables (`$container->add('foo', 'bar')`) cannot be resolved in any way without `ReflectionContainer`, isn't accessing them ServiceLocator pattern?
And I understand that ServiceLocator is anti-pattern... What should one think of it?

**Comment by philipobenito** [comment] 2018-04-02 10:45
I'm not sure I understand the question.

The container ideally is only a map of your classes and their dependencies, not really a key value store, I wouldn't recommend just storing values in it, if it's config, maybe a config object or something would be better.

That being said, you can't get a named argument from the container using the `ReflectionContainer` so I'm not sure what you mean by:

> (`$container->add('foo', 'bar')`) cannot be resolved in any way without ReflectionContainer

That is the opposite way around, if you wanted `foo`, you would just call `$container->get('foo')` or add it as an argument to another dependency `$container->add('something_else', 'SomethingElse')->withArgument('foo');`.
